### ISSUE TITLE
Não consigo criar conta

### ISSUE THREAD

**Issue by notdanilo** [OpenBanking-Brasil/areadesenvolvedor#125]
Estou usando o e-mail da minha empresa com domínio sensorial.systems, porém suspeito que as regras de filtro não permitem.
Também tentei usar meu e-mail pessoal gmail.com, mas recebo uma mensagem dizendo que e-mails pessoais não são permitidos.

https://auth.directory.openbankingbrasil.org.br/interaction/c8lTLEe6_WgzZ_XCEdSEn

**Comment by GislaineAlmeida** [comment]
Boa noite, necessário abrir ticket no service desk.
