### ISSUE TITLE
Open Banking para pessoa física

### ISSUE THREAD

**Issue by notdanilo** [OpenBanking-Brasil/areadesenvolvedor#127]
Pelo o que tenho me informado as APIs não são muito úteis para pessoas físicas.

Em algum momento APIs serão disponibilizadas para automação de operações bancárias?

**Comment by GislaineAlmeida** [comment]
As APIs do Open Banking Brasil estão sendo criadas para que aplicativos desenvolvidos por instituições financeiras tradicionais e também fintechs possam trocar informações dos clientes  de forma padronizada desde que com prévia coleta de consentimento. Elas realmente não estão planejadas para uso direto pelo usuário final.
