### ISSUE TITLE
API - Accounts | saldos-da-conta | availableAmount #9

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/areadesenvolvedor#157]
https://openbanking-brasil.github.io/areadesenvolvedor/#saldos-da-conta
https://openbanking-brasil.github.io/areadesenvolvedor/swagger/swagger_accounts_apis.yaml

        availableAmount:
          type: number
          format: double
          pattern: '(-?\d{15}(.\d{4}?))$'
          description: 'Saldo disponível para utilização imediata. No caso de conta de depósito a vista, sem considerar cheque especial e investimentos atrelados a conta. Admite saldo negativo. Expresso em valor monetário com 4 casas decimais.'
          maxLength: 19
          minLength: 0
          nullable: true
          example: 100000.04
pattern does not correspond to double format and to example specified

**Comment by EkkeErick** [comment]
Hey Ralph,
 
We are going to fix the regex. We plan to release a new versionon 14/06 or on 15/06.
 
The regex shall be fixed and will be replaced by '(-?\d{1,15}(.?\d{0,4}?))$'
