### ISSUE TITLE
Consent transaction filters

### ISSUE THREAD

**Issue by samlarsen1** [OpenBanking-Brasil/areadesenvolvedor#158]
Original ticket: https://github.com/OpenBanking-Brasil/specs-seguranca/issues/99

The transaction date filters defined in consent seem to only be documented in the consent swagger definition - the description is not definitive enough for people to understand. I can't find any more guidance to point people to for this requirement.

"transactionFromDateTime": "2021-01-01T00:00:00Z",
"transactionToDateTime": "2021-02-01T23:59:59Z"

Are these in scope? We assume they are, they are in the consent spec - if so, we need more documentation to describe the general concepts of both consent transaction date filters and transaction API date filters.

**Comment by samlarsen1** [comment]
This concept has been missed by a number of people i have spoken to.

I think there should be a general description of this concept like we have in the uk:

https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/account-and-transaction-api-profile.html#transaction-to-from-date-time

**Comment by GislaineAlmeida** [comment]
Hello
The transaction date filters are optional in our specification and everything indicates that we can remove it in a future version. It came from british model but, once that here we have the consent defined in range periods(6 months, 12 months) this dates lost significance. So in your request for a consent you don't need to send this dates in the payload.

**Comment by samlarsen1** [comment]
@GislaineAlmeida they are optional for a TPP - but mandatory for an ASPSP?  As an ASPSP do we have to build that functionality or not?  If not, it should be removed from the spec
