### ISSUE TITLE
Lista de contratos

### ISSUE THREAD

**Issue by ederjorge-banfico** [OpenBanking-Brasil/areadesenvolvedor#16]
Olá pessoal.

Estava explorando as APIs da fase 2, e vi que existe uma API de operações de crédito. Os gets das apis pedem um `contractId`, que eu entendi que temos que pegar do `ipocCode` depois de um parse neste campo. 
O que eu não encontrei foi como pegar a lista de contratos de uma pessoa jurídica ou de uma pessoa física. Sei que ainda estão trabalhando nas especificações, mas não entendi como chegar no contrato se não tenho como recuperar esta informação de outro endpoint.

Por favor, podem esclarecer este ponto, e me corrigir se eu estiver errado?

Obrigado.

**Comment by ederjorge-banfico** [comment]
Eu abri um ticket no service desk do open banking br: https://servicedesk.openbankingbrasil.org.br/Login.jsp?navLanguage=pt-BR

**Comment by ederjorge-banfico** [comment]
Recebi esta resposta. Fico aguardando.

> Esse ponto ainda está em fase de definição.
> Mais detalhes serão publicados em breve no Portal do Desenvolvedor (https://openbanking-brasil.github.io/areadesenvolvedor/#introducao)

**Comment by paulovitorbal** [comment]
Poderiam marcar na documentação quais pontos ainda estão em definição. 🤔

**Comment by GislaineAlmeida** [comment]
As APIs como um todo estão sob revisão com entrega final nos próximos dias, são muitos ajustes nos dicionários/schemas de resposta, muitos mesmo. Quanto ao contractId deves ter visto que todas as APIs de dados, a exceção de Customers, têm um listar(GET sem parâmetros). É dali que virão os IDs necessários, desde que exista consentimento AUTHORISED (com "S" mesmo, padrão do inglês britânico) para os recursos da API em questão.
