### ISSUE TITLE
DELETE Consent API errata?

### ISSUE THREAD

**Issue by alexasensio** [OpenBanking-Brasil/areadesenvolvedor#162]
At the end of Github's [DELETE /consents API](https://openbanking-brasil.github.io/areadesenvolvedor/#deletar-revogar-o-consentimento-identificado-por-consentid) specification it mentions that " This operation does not require authentication".

However the swagger requires an access token:
![Screenshot 2021-06-14 at 10 43 40](https://user-images.githubusercontent.com/9254804/121872649-6cdac180-ccfd-11eb-83e5-730cd9e0764b.png)

This is more in line with what is expected, and it follows the same authentication requirements than the POST and GET methods.

1. Is the swagger correct and therefore in Github there is an errata?
2. If so, can we assume that the required scope for DELETE /consents is also "consents"?

**Comment by GislaineAlmeida** [comment]
1. Yes, swagger is correct.
2. Yes, consents.

**Comment by alexasensio** [comment]
Thanks for replying @GisAlmeida . 
I suggest this changes are included in the following PR, otherwise the information will still be unclear to the rest of the audience
