### ISSUE TITLE
Dúvida com o response em caso de erro durante a criação de consentimento

### ISSUE THREAD

**Issue by AdsonVieira** [OpenBanking-Brasil/areadesenvolvedor#274]
Segundo a documentação alguns status http devem ser retornados da seguinte [forma.](https://openbanking-brasil.github.io/areadesenvolvedor/#tocS_ResponseError)  Na documentação não fica claro quais os valores devo aplicar nos atributos `code`, `title` e `detail`.
Essa dúvida surge por conta do **422ResponseErrorCreateConsent** onde temos a especificação desse valores. Como proceder nesses casos, alguém já passou por esse problema?

1. 422ResponseErrorCreateConsent

- https://openbanking-brasil.github.io/areadesenvolvedor/#tocS_422ResponseErrorCreateConsent

**Comment by horochovec** [comment]
@AdsonVieira 

Os possíveis códigos de retorno do JSON no atributo **code**:
- FORMA_PGTO_INVALIDA
- DATA_PGTO_INVALIDA
- DETALHE_PGTO_INVALIDO
- NAO_INFORMADO

As mensagens do JSON para o atributo **title** de acordo com cada **code**:
- FORMA_PGTO_INVALIDA: Forma de pagamento inválida.
- DATA_PGTO_INVALIDA: Data de pagamento inválida.
- DETALHE_PGTO_INVALIDO: Detalhe do pagamento inválido.
- NAO_INFORMADO: Não informado.

As mensagens do JSON para o atributo **detail** de acordo com cada **code**:
- FORMA_PGTO_INVALIDA – Meio de pagamento inválido.
- DATA_PGTO_INVALIDA – Data de pagamento inválida no contexto, por exemplo, data no passado. Para pagamentos únicos deve ser informada a data atual, do dia corrente.
- DETALHE_PGTO_INVALIDO: O campo [nome_campo] não atende os requisitos de preenchimento.
- NAO_INFORMADO – Não reportado/identificado pela instituição detentora de conta.
