### ISSUE TITLE
Item RESOURCES_READ faltante nas enums

### ISSUE THREAD

**Issue by jotafeldmann** [OpenBanking-Brasil/areadesenvolvedor#68]
Olá :)

Dúvida: O item `RESOURCES_READ` deveria estar listado em https://github.com/OpenBanking-Brasil/areadesenvolvedor/blob/master/documentation/source/dictionary/consents_list.csv ? 🤔 

Além disso, temos os seguintes resultados:

- 7 resultados para `RESOURCES_READ`
https://github.com/OpenBanking-Brasil/areadesenvolvedor/search?q=RESOURCES_READ

- 14 para `ACCOUNTS_READ`
https://github.com/OpenBanking-Brasil/areadesenvolvedor/search?q=ACCOUNTS_READ

O `RESOURCES_READ` é de alguma categoria/hierarquia diferente?

**Comment by GislaineAlmeida** [comment]
Incluso.
